name = "12_intonation"

[soundfile.intonation-0]
path = "tapes/12_intonation/12_intonation_0.wav"

[soundfile.intonation-1]
path = "tapes/12_intonation/12_intonation_1.wav"

[soundfile.intonation-2]
path = "tapes/12_intonation/12_intonation_2.wav"

[soundfile.intonation-3]
path = "tapes/12_intonation/12_intonation_3.wav"

[soundfile.intonation-4]
path = "tapes/12_intonation/12_intonation_4.wav"

[soundfile.intonation-5]
path = "tapes/12_intonation/12_intonation_5.wav"

[soundfile.intonation-6]
path = "tapes/12_intonation/12_intonation_6.wav"

[soundfile.intonation-7]
path = "tapes/12_intonation/12_intonation_7.wav"

[soundfile.intonation-8]
path = "tapes/12_intonation/12_intonation_8.wav"

[soundfile.intonation-9]
path = "tapes/12_intonation/12_intonation_9.wav"

[soundfile.intonation-10]
path = "tapes/12_intonation/12_intonation_10.wav"

[soundfile.intonation-11]
path = "tapes/12_intonation/12_intonation_11.wav"

[soundfile.intonation-12]
path = "tapes/12_intonation/12_intonation_12.wav"

[audio.channel_mapping]
# first channel is reserved for electronic instrument ('aobjects')
0 = 1
